---
on:
  pull_request:
  push:
    branches: [ master ]

name: pre-commit

jobs:
  pre-commit:
    runs-on: sonar-xs
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: SonarSource/gh-action_pre-commit@master
